import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import compression from 'compression';
import xss from 'xss-clean';
import mongoose from 'mongoose';
import mongoSanitize from 'express-mongo-sanitize';
import { Server as SocketServer } from 'socket.io';
import connectDB from './config/db.js';
import { protect } from './middleware/auth.js';
import { notFound, errorHandler } from './middleware/errorHandler.js';
import { requestLogger } from './middleware/requestLogger.js';
import { authorizePermission } from './middleware/permissions.js';
import authRoutes from './routes/authRoutes.js';
import inventoryRoutes from './routes/inventoryRoutes.js';
import orderRoutes from './routes/orderRoutes.js';
import reportRoutes from './routes/reportRoutes.js';
import settingRoutes from './routes/settingRoutes.js';
import securityRoutes from './routes/securityRoutes.js';
import userRoutes from './routes/userRoutes.js';
import accountingRoutes from './routes/accountingRoutes.js';
import { customerRoutes, employeeRoutes, attendanceRoutes } from './routes/resourceRoutes.js';

const app = express();
if (process.env.TRUST_PROXY === 'true') app.set('trust proxy', 1);
app.use(helmet());
const allowedOrigins = (process.env.CLIENT_URL || '').split(',').map(origin => origin.trim()).filter(Boolean);
app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.length === 0 || allowedOrigins.includes(origin) ? callback(null, true) : callback(new Error('Origin not allowed by CORS')), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(compression()); app.use(mongoSanitize()); app.use(xss()); app.use(requestLogger);
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 100, standardHeaders: true, legacyHeaders: false }));
app.get('/', (req, res) => res.json({ success: true, service: 'two-ms-veil-api', message: 'Factory management API is running' }));
app.get('/health', (req, res) => res.json({ success: true, service: 'two-ms-veil-api', version: process.env.APP_VERSION || '1.0.0', database: mongoose.connection.readyState === 1 ? 'connected' : 'disconnected', memory: { rss: process.memoryUsage().rss, heapUsed: process.memoryUsage().heapUsed } }));
app.use('/api/auth', authRoutes);
app.use('/api/security', securityRoutes);
app.use('/api/users', userRoutes);
app.use('/api/accounting', accountingRoutes);
app.use('/api/customers', protect, authorizePermission('customers'), customerRoutes);
app.use('/api/orders', protect, authorizePermission('orders'), orderRoutes);
app.use('/api/inventory', protect, authorizePermission('inventory'), inventoryRoutes);
app.use('/api/employees', protect, authorizePermission('employees'), employeeRoutes);
app.use('/api/attendance', protect, authorizePermission('attendance'), attendanceRoutes);
app.use('/api/reports', protect, authorizePermission('reports'), reportRoutes);
app.use('/api/settings', protect, authorizePermission('settings'), settingRoutes);
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/security', securityRoutes);
app.use('/api/v1/users', userRoutes);
app.use('/api/v1/accounting', accountingRoutes);
app.use('/api/v1/customers', protect, authorizePermission('customers'), customerRoutes);
app.use('/api/v1/orders', protect, authorizePermission('orders'), orderRoutes);
app.use('/api/v1/inventory', protect, authorizePermission('inventory'), inventoryRoutes);
app.use('/api/v1/employees', protect, authorizePermission('employees'), employeeRoutes);
app.use('/api/v1/attendance', protect, authorizePermission('attendance'), attendanceRoutes);
app.use('/api/v1/reports', protect, authorizePermission('reports'), reportRoutes);
app.use('/api/v1/settings', protect, authorizePermission('settings'), settingRoutes);
app.use(notFound);
app.use(errorHandler);

const port = Number(process.env.PORT) || 5000;
let server;
if (process.env.NODE_ENV !== 'test') connectDB().then(() => { server = app.listen(port, () => console.log(`API listening on port ${port}`)); const io = new SocketServer(server, { cors: { origin: allowedOrigins.length ? allowedOrigins : true, credentials: true } }); io.on('connection', socket => socket.emit('connected', { version: process.env.APP_VERSION || '1.0.0' })); }).catch(error => { console.error(error); process.exit(1); });
async function shutdown(signal) { console.log(`${signal}: shutting down`); if (server) await new Promise(resolve => server.close(resolve)); await mongoose.disconnect(); process.exit(0); }
process.once('SIGTERM', () => shutdown('SIGTERM')); process.once('SIGINT', () => shutdown('SIGINT'));
export default app;
