import { Bell, ChevronDown, Home, Languages, Moon, Sun, UserCircle, X } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { useStore } from '../store';
import { connectNotifications, useNotifications } from '../notifications';

const labels = { orders: 'অর্ডার', customers: 'কাস্টমার', inventory: 'ইনভেন্টরি', employees: 'কর্মী', attendance: 'হাজিরা', reports: 'রিপোর্টস', settings: 'সেটিংস', profile: 'প্রোফাইল' };

export default function Header({ onMenu }) {
  const location = useLocation(); const navigate = useNavigate(); const user = useStore(s => s.user); const theme = useStore(s => s.theme); const setTheme = useStore(s => s.setTheme); const logout = useStore(s => s.logout); const items = useNotifications(s => s.items); const markAllRead = useNotifications(s => s.markAllRead); const [profileOpen, setProfileOpen] = useState(false); const [notificationsOpen, setNotificationsOpen] = useState(false); const [language, setLanguage] = useState(localStorage.getItem('factory_language') || 'bn');
  useEffect(() => connectNotifications(), []);
  const crumbs = location.pathname.split('/').filter(Boolean);
  function toggleLanguage() { const next = language === 'bn' ? 'en' : 'bn'; localStorage.setItem('factory_language', next); setLanguage(next); }
  return <><header className="top-header"><div className="header-brand"><button className="icon-btn header-menu" aria-label="মেনু খুলুন" onClick={onMenu}>☰</button><span>Two M-s Veil</span></div><div className="header-actions"><button className="icon-btn header-control" aria-label="ভাষা পরিবর্তন" onClick={toggleLanguage}><Languages size={18}/><small>{language.toUpperCase()}</small></button><button className="icon-btn header-control" aria-label="থিম পরিবর্তন" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>}</button><div className="header-popover-wrap"><button className="icon-btn header-control notification-control" aria-label="নোটিফিকেশন" aria-expanded={notificationsOpen} onClick={() => { setNotificationsOpen(!notificationsOpen); setProfileOpen(false); }}><Bell size={19}/>{items.some(item => !item.read) && <i/>}</button>{notificationsOpen && <div className="header-popover notification-popover"><div className="popover-head"><b>নোটিফিকেশন</b><button className="icon-btn" aria-label="বন্ধ করুন" onClick={() => setNotificationsOpen(false)}><X size={15}/></button></div>{items.length ? items.map(item => <div className="notification-item" key={item.id}><span className={`notification-dot ${item.type}`}/><div><b>{item.message}</b><small>{new Date(item.createdAt).toLocaleString('bn-BD')}</small></div></div>) : <div className="notification-item">কোনো নোটিফিকেশন নেই</div>}<button className="mark-read" onClick={markAllRead}>সব পড়া হয়েছে</button></div>}</div><div className="header-popover-wrap"><button className="profile-trigger" aria-label="প্রোফাইল মেনু" aria-expanded={profileOpen} onClick={() => { setProfileOpen(!profileOpen); setNotificationsOpen(false); }}><span className="profile-avatar">{(user?.name || 'U').slice(0, 1).toUpperCase()}</span><span className="profile-copy"><b>{user?.name || 'User'}</b><small>{user?.role || 'staff'}</small></span><ChevronDown size={15}/></button>{profileOpen && <div className="header-popover profile-popover"><div className="profile-popover-head"><UserCircle size={27}/><div><b>{user?.name || 'User'}</b><small>{user?.email || ''}</small></div></div><Link to="/profile" onClick={() => setProfileOpen(false)}>প্রোফাইল</Link><Link to="/settings" onClick={() => setProfileOpen(false)}>সেটিংস</Link>{user?.role === 'admin' && <Link to="/security/2fa" onClick={() => setProfileOpen(false)}>2FA Setup</Link>}<button onClick={() => { logout(); navigate('/login'); }}>লগ আউট</button></div>}</div></div></header><nav className="breadcrumbs" aria-label="ব্রেডক্রাম্ব"><Link to="/"><Home size={14}/> হোম</Link>{crumbs.map((crumb, index) => <span key={crumb}><b>›</b>{index === crumbs.length - 1 ? <strong>{labels[crumb] || crumb}</strong> : <Link to={`/${crumb}`}>{labels[crumb] || crumb}</Link>}</span>)}</nav></>;
}
