import asyncHandler from '../utils/asyncHandler.js';
import mongoose from 'mongoose';
import Order from '../models/Order.js';
import Inventory from '../models/Inventory.js';
import { consumeFIFO } from '../utils/fifo.js';
import { TRACKING_STEPS } from '../config/constants.js';
import { audit } from '../utils/audit.js';
function trackingFor(status) { const index = { Pending: 0, Processing: 1, Ready: 3, Delivered: 4, Cancelled: -1 }[status]; return TRACKING_STEPS.map((step, i) => ({ step, status: status === 'Cancelled' ? 'pending' : i < index ? 'done' : i === index ? 'active' : 'pending', time: i <= index ? new Date() : undefined })); }
function totals(body) { const gross = Number(body.quantity || 0) * Number(body.unit_price || 0); const discount = Number(body.discount || 0); const total = Math.max(0, gross - discount); return { total_price: total, due_amount: Math.max(0, total - Number(body.advanced_paid || 0)) }; }
export const listOrders = asyncHandler(async (req, res) => { const query = { isDeleted: false }; if (req.query.status) query.status = req.query.status; if (req.query.search) query.$or = [{ customer_name: new RegExp(req.query.search, 'i') }, { product_type: new RegExp(req.query.search, 'i') }]; const page = Math.max(Number(req.query.page) || 1, 1); const limit = Math.min(Math.max(Number(req.query.limit) || 25, 1), 100); const [data, total] = await Promise.all([Order.find(query).sort({ order_date: -1 }).skip((page - 1) * limit).limit(limit).lean().populate('customer_id product_id'), Order.countDocuments(query)]); res.json({ success: true, data, pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); });
export const createOrder = asyncHandler(async (req, res) => { const customer = req.body.customer_id; const data = await Order.create({ ...req.body, ...totals(req.body), tracking: trackingFor('Pending') }); res.status(201).json({ success: true, data: await data.populate('customer_id product_id') }); });
export const updateOrder = asyncHandler(async (req, res) => { const allowed = ['status', 'delivery_date', 'note', 'product_id', 'unit_price', 'quantity', 'discount', 'advanced_paid']; const changes = Object.fromEntries(Object.entries(req.body).filter(([key]) => allowed.includes(key))); const current = await Order.findById(req.params.id); if (!current) { res.status(404); throw new Error('Order not found'); } Object.assign(current, changes, totals({ ...current.toObject(), ...changes })); if (changes.status) current.tracking = trackingFor(changes.status); await current.save(); res.json({ success: true, data: await current.populate('customer_id product_id') }); });
export const updateStatus = asyncHandler(async (req, res) => { const { status } = req.body; if (!['Processing', 'Ready', 'Delivered', 'Cancelled'].includes(status)) { res.status(400); throw new Error('Invalid manual status'); } const data = await Order.findOneAndUpdate({ _id: req.params.id, isDeleted: false }, { status, tracking: trackingFor(status) }, { new: true, runValidators: true }).populate('customer_id product_id'); if (!data) { res.status(404); throw new Error('Order not found'); } await audit(req, 'order.status.updated', 'Order', data._id, { status }); res.json({ success: true, data }); });
export const processFIFO = asyncHandler(async (req, res) => { const session = await mongoose.startSession(); let processed; try { await session.withTransaction(async () => { const order = await Order.findOne({ _id: req.params.id, isDeleted: false }).session(session); if (!order) { res.status(404); throw new Error('Order not found'); } if (!order.product_id) { res.status(400); throw new Error('Order has no inventory product'); } if (order.cogs > 0 || order.status === 'Ready') { res.status(409); throw new Error('Order has already been processed'); } const inventory = await Inventory.findOne({ _id: order.product_id, isDeleted: false }).session(session); if (!inventory) { res.status(404); throw new Error('Inventory item not found'); } const { cogs } = consumeFIFO(inventory, order.quantity); order.cogs = cogs; order.profit = order.total_price - cogs; order.profit_margin = order.total_price ? (order.profit / order.total_price) * 100 : 0; order.status = 'Ready'; order.tracking = trackingFor('Ready'); await inventory.save({ session }); await order.save({ session }); processed = order; }); } finally { await session.endSession(); } res.json({ success: true, data: await processed.populate('customer_id product_id') }); });
